name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - name: Install Typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.7.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar xf typst-x86_64-unknown-linux-musl.tar.xz
          echo "$PWD/typst-x86_64-unknown-linux-musl" >> $GITHUB_PATH
      - name: Compile
        run: |
          mkdir ./_site
          typst compile ./main.typ ./_site/main.pdf
      - uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: compile
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
